/*
    bit.h -- Build It Configuration Header for macosx-x86_64

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

#define BLD_PRODUCT "pcre"
#define BLD_NAME "PCRE Library"
#define BLD_COMPANY "Embedthis"
#define BLD_PCRE_PRODUCT 1
#define BLD_VERSION "1.0.0"
#define BLD_NUMBER "B0"
#define BLD_MAJOR_VERSION 1
#define BLD_MINOR_VERSION 0
#define BLD_PATCH_VERSION 0
#define BLD_VNUM 100000000
#define BLD_CONFIG_CMD "bit -q -d -without all configure -gen sh,make,xcode"
#define BLD_LIB_NAME "bin"
#define BLD_CFG_PREFIX "/etc/pcre"
#define BLD_BIN_PREFIX "/usr/lib/pcre/1.0.0/bin"
#define BLD_DOC_PREFIX "/usr/lib/pcre/doc"
#define BLD_INC_PREFIX "/usr/lib/pcre/1.0.0/inc"
#define BLD_JEM_PREFIX "/usr/lib/pcre/jems"
#define BLD_LIB_PREFIX "/usr/lib/pcre/1.0.0/bin"
#define BLD_LOG_PREFIX "/var/log/pcre"
#define BLD_MAN_PREFIX "/usr/lib/pcre/man"
#define BLD_PRD_PREFIX "/usr/lib/pcre"
#define BLD_SAM_PREFIX "/usr/lib/pcre/samples"
#define BLD_SPL_PREFIX "/var/spool/pcre"
#define BLD_SRC_PREFIX "/usr/src/pcre-1.0.0"
#define BLD_VER_PREFIX "/usr/lib/pcre/1.0.0"
#define BLD_WEB_PREFIX "/var/www/pcre-default"
#define BLD_EXE ""
#define BLD_SHLIB ".dylib"
#define BLD_SHOBJ ".dylib"
#define BLD_LIB ".a"
#define BLD_OBJ ".o"
#define BLD_CC_DOUBLE_BRACES 1
#define BLD_CC_DYN_LOAD 1
#define BLD_CC_EDITLINE 1
#define BLD_CC_MMU 1
#define BLD_CC_MTUNE 1
#define BLD_CC_PAM 0
#define BLD_CC_STACK_PROTECTOR 1
#define BLD_CC_SYNC 1
#define BLD_CC_SYNC_CAS 0
#define BLD_CC_UNNAMED_UNIONS 1
#define BLD_CC_WARN_64TO32 1
#define BLD_CC_WARN_UNUSED 1
#define BLD_FEATURE_ALL 0
#define BLD_FEATURE_CC 1
#define BLD_CC "/usr/bin/clang"
#define BLD_FEATURE_LINK 1
#define BLD_LINK "/usr/bin/ld"
