/*
    bit.h -- Build It Configuration Header for solaris-x86

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

/* Settings */
#define BIT_BUILD_NUMBER "B0"
#define BIT_COMPANY "Embedthis"
#define BIT_DEPTH 1
#define BIT_HAS_DOUBLE_BRACES 1
#define BIT_HAS_DYN_LOAD 1
#define BIT_HAS_LIB_EDIT 0
#define BIT_HAS_MMU 1
#define BIT_HAS_MTUNE 1
#define BIT_HAS_PAM 0
#define BIT_HAS_STACK_PROTECTOR 1
#define BIT_HAS_SYNC 0
#define BIT_HAS_SYNC_CAS 0
#define BIT_HAS_UNNAMED_UNIONS 1
#define BIT_OPTIONAL ""
#define BIT_PRODUCT "pcre"
#define BIT_REQUIRED "compiler,link"
#define BIT_SYNC ""
#define BIT_TITLE "PCRE Library"
#define BIT_VERSION "1.0.0"
#define BIT_WARN64TO32 0
#define BIT_WARN_UNUSED 0

/* Prefixes */
#define BIT_CFG_PREFIX "/etc/pcre"
#define BIT_BIN_PREFIX "/usr/lib/pcre/1.0.0/bin"
#define BIT_INC_PREFIX "/usr/lib/pcre/1.0.0/inc"
#define BIT_LOG_PREFIX "/var/log/pcre"
#define BIT_PRD_PREFIX "/usr/lib/pcre"
#define BIT_SPL_PREFIX "/var/spool/pcre"
#define BIT_SRC_PREFIX "/usr/src/pcre-1.0.0"
#define BIT_VER_PREFIX "/usr/lib/pcre/1.0.0"
#define BIT_WEB_PREFIX "/var/www/pcre-default"

/* Suffixes */
#define BIT_EXE ""
#define BIT_SHLIB ".so"
#define BIT_SHOBJ ".so"
#define BIT_LIB ".a"
#define BIT_OBJ ".o"

/* Profile */
#define BIT_PCRE_PRODUCT 1
#define BIT_PROFILE "debug"
#define BIT_CONFIG_CMD "bit -d -q -platform solaris-x86 -without all -configure . -gen sh,make"

/* Miscellaneous */
#define BIT_MAJOR_VERSION 1
#define BIT_MINOR_VERSION 0
#define BIT_PATCH_VERSION 0
#define BIT_VNUM 100000000

/* Packs */
#define BIT_PACK_ALL 0
#define BIT_PACK_CC 1
#define BIT_PACK_LINK 1
