/*
    bit.h -- Build It Configuration Header for solaris-x86

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

#define BIT_PRODUCT "pcre"
#define BIT_NAME "PCRE Library"
#define BIT_COMPANY "Embedthis"
#define BIT_PCRE_PRODUCT 1
#define BIT_VERSION "1.0.0"
#define BIT_NUMBER "B0"
#define BIT_MAJOR_VERSION 1
#define BIT_MINOR_VERSION 0
#define BIT_PATCH_VERSION 0
#define BIT_VNUM 100000000
#define BIT_CONFIG_CMD "bit -d -q -platform solaris-x86 -without all -configure . -gen sh,make"
#define BIT_PROFILE "debug"
#define BIT_CFG_PREFIX "/etc/pcre"
#define BIT_BIN_PREFIX "/usr/lib/pcre/1.0.0/bin"
#define BIT_INC_PREFIX "/usr/lib/pcre/1.0.0/inc"
#define BIT_LOG_PREFIX "/var/log/pcre"
#define BIT_PRD_PREFIX "/usr/lib/pcre"
#define BIT_SPL_PREFIX "/var/spool/pcre"
#define BIT_SRC_PREFIX "/usr/src/pcre-1.0.0"
#define BIT_VER_PREFIX "/usr/lib/pcre/1.0.0"
#define BIT_WEB_PREFIX "/var/www/pcre-default"
#define BIT_EXE ""
#define BIT_SHLIB ".so"
#define BIT_SHOBJ ".so"
#define BIT_LIB ".a"
#define BIT_OBJ ".o"
#define BIT_CC_DOUBLE_BRACES 1
#define BIT_CC_DYN_LOAD 1
#define BIT_CC_EDITLINE 0
#define BIT_CC_MMU 1
#define BIT_CC_MTUNE 1
#define BIT_CC_PAM 0
#define BIT_CC_STACK_PROTECTOR 1
#define BIT_CC_SYNC 0
#define BIT_CC_SYNC_CAS 0
#define BIT_CC_UNNAMED_UNIONS 1
#define BIT_CC_WARN_64TO32 0
#define BIT_CC_WARN_UNUSED 0
#define BIT_FEATURE_ALL 0
#define BIT_FEATURE_CC 1
#define BIT_FEATURE_LINK 1
