/*
    bit.h -- Build It Configuration Header for windows-x86

    This header is generated by Bit during configuration.
    You may edit this file, but Bit will overwrite it next
    time configuration is performed.
 */

/* Settings */
#define BIT_BUILD_NUMBER "B0"
#define BIT_COMPANY "Embedthis"
#define BIT_DEPTH 1
#define BIT_HAS_DYN_LOAD 1
#define BIT_HAS_LIB_EDIT 0
#define BIT_HAS_MMU 1
#define BIT_HAS_UNNAMED_UNIONS 1
#define BIT_OPTIONAL ""
#define BIT_PRODUCT "pcre"
#define BIT_REQUIRED "winsdk,compiler,link,dumpbin,rc"
#define BIT_SYNC ""
#define BIT_TITLE "PCRE Library"
#define BIT_VERSION "1.0.0"

/* Prefixes */
#define BIT_CFG_PREFIX "C:/Program Files (x86)/PCRE Library"
#define BIT_BIN_PREFIX "C:/Program Files (x86)/PCRE Library/bin"
#define BIT_INC_PREFIX "C:/Program Files (x86)/PCRE Library/inc"
#define BIT_LOG_PREFIX "C:/Program Files (x86)/PCRE Library/logs"
#define BIT_PRD_PREFIX "C:/Program Files (x86)/PCRE Library"
#define BIT_SPL_PREFIX "C:/Program Files (x86)/PCRE Library/tmp"
#define BIT_SRC_PREFIX "C:/Program Files (x86)/PCRE Library/src"
#define BIT_VER_PREFIX "C:/Program Files (x86)/PCRE Library"
#define BIT_WEB_PREFIX "C:/Program Files (x86)/PCRE Library/web"

/* Suffixes */
#define BIT_EXE ".exe"
#define BIT_SHLIB ".lib"
#define BIT_SHOBJ ".dll"
#define BIT_LIB ".a"
#define BIT_OBJ ".obj"

/* Profile */
#define BIT_PCRE_PRODUCT 1
#define BIT_PROFILE "vs"
#define BIT_CONFIG_CMD "bit -d -q -platform windows-x86 -without all -profile vs -configure . -gen vs"

/* Miscellaneous */
#define BIT_MAJOR_VERSION 1
#define BIT_MINOR_VERSION 0
#define BIT_PATCH_VERSION 0
#define BIT_VNUM 100000000

/* Packs */
#define BIT_PACK_ALL 0
#define BIT_PACK_CC 1
#define BIT_PACK_DUMPBIN 0
#define BIT_PACK_LINK 1
#define BIT_PACK_RC 1
#define BIT_PACK_WINSDK 1
